config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  root 'pages#index'

  get 'about' => "pages#about"
  get 'location' => "pages#location"

end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :phone, :string
  attr_accessor :message, :string

  validates_presence_of :name
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_presence_of :phone
  validates_presence_of :message
  validates_length_of :message, :maximum => 500

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      UserMailer.contact_email(@contact).deliver
      flash[:success] = "Message sent from #{@contact.name}."
      redirect_to new_contact_path
    else
      flash.now[:danger] = "Message not sent.  Please see errors below."
      render :new
    end
  end


  private

  def secure_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def location
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="box">
  <div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">Contact
      <strong>Us</strong>
    </h2>
    <hr>
    <div class="col-md-6">
      <%= image_tag("james.jpg", :class => "img-responsive img-border-left") %>
    </div>
    <div class="col-md-6">
      <p><strong>Address:</strong>
        <br>101 Hollingsworth Drive
        <br>Glencoe, AL 35905
      </p>
      <p><strong>Phone:</strong>
        <br>256.494.0244
      </p>
      <p><strong>Fax:</strong>
        <br>256.494.0257
      </p>
      <p><strong>Email:</strong>
        <br><%= mail_to "nemethgrinding@cableone.net" %>
      </p>
    </div>
    <div class="clearfix"></div>
    <hr>
    <p>Have a question?  Want a quote?  Send us a message below, and we will get back as soon as possible.</p><br>
      <div class="row">
        <%= form_for @contact, html: { :multipart => true } do |f| %>
          <% if @contact.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this article from being saved:</h2>

              <ul>
              <% @contact.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group col-lg-12">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group col-lg-12">
              <%= f.label :email %>
              <%= f.text_field :email, class: "form-control" %>
            </div>
            <div class="form-group col-lg-12">
              <%= f.label :phone %>
              <%= f.text_field :phone, class: "form-control" %>
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-lg-12">
              <%= f.label :message %>
              <%= f.text_area :message, as: :text, :rows => "6", class: "form-control" %>
            </div>
            <div class="form-group col-lg-4">
              <%= f.submit "Submit", class: "btn btn-default" %>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <p>Nemeth Grinding | Phone 256.494.0244 | Fax 256.494.0257</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="brand">Nemeth Grinding</div>
<div class="address-bar"> 101 Hollingsworth Drive | Glencoe, AL 35905 | 256.494.0244</div>
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Nemeth Grinding", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Location", location_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nemeth Grinding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">Our
        <strong>Capabilities</strong>
      </h2>
      <hr>
    </div>
    <div class="col-md-6">
      <%= image_tag("slide1.jpg", :class => "img-responsive img-border-left") %>
    </div>
    <div class="col-md-6">
        <p>We pride ourselves in providing high quality grinding services with fast turnaround times.</p>
        <p>Add capacity abilities, etc HERE</p>

    </div>
    <div class="clearfix"></div>
  </div>

  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">Our
        <strong>Equipment</strong>
      </h2>
      <hr>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("120blanchard2.jpg", :class => "img-responsive") %>
      <p>
        <small>72HD-120 - "The Big Blanchard"</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("120blanchard.jpg", :class => "img-responsive") %>
      <p>
        <small>72HD-120 - "The Big Blanchard"</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("36HD66.jpg", :class => "img-responsive") %>
      <p>
        <small>36HD-66</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("26HD48.jpg", :class => "img-responsive") %>
      <p>
        <small>26HD-48</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("18_36.jpg", :class => "img-responsive") %>
      <p>
        <small>18HD-36</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("forklift.jpg", :class => "img-responsive") %>
      <p>
        <small>13.5k Hyster Forklift</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("cranes1.jpg", :class => "img-responsive") %>
      <p>
        <small>15 & 2 Ton Overhead Cranes + Eriez Lift Magnets, 2 to 10 Tons</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("cranes2.jpg", :class => "img-responsive") %>
      <p>
        <small>1 Ton Overhead Crane</small>
      </p>
    </div>

    <div class="col-sm-6 text-center">
      <%= image_tag("str8press.jpg", :class => "img-responsive") %>
      <p>
        <small>Straightening Press</small>
      </p>
    </div>

    <div class="clearfix"></div>
  </div>

app/views/pages/index.html.erb
<div class="box">
    <div class="col-lg-12 text-center">
      <div id="carousel-example-generic" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators hidden-xs">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag("slide1.jpg", :class => "img-responsive img-full") %>
          </div>
          <div class="item">
            <%= image_tag("slide2.jpg", :class => "img-responsive img-full") %>
          </div>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="icon-next"></span>
        </a>
      </div>
      <h2 class="brand-before">
        <small>Welcome to</small>
      </h2>
      <h1 class="brand-name">Nemeth Grinding</h1>
      <hr class="tagline-divider">
      <h2 class="intro-text text-center">
        <strong>For All Your Precision Grinding Needs</strong>
      </h2>
    </div>

  </div>

  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">High Capacity.<strong>  Fast Turnaround.</strong>
      </h2>
      <hr>
      <p>We pride ourselves on being .... FINISH FILLING IN INFO.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
    </div>
  </div>

app/views/pages/location.html.erb
<div class="box">
  <div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">Our
      <strong>Location</strong>
    </h2>
    <hr>
  </div>
  <div class="col-md-8">
    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
    <iframe width="100%" height="400" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=Nemeth%20Grinding%2C%20Hollingsworth%20Drive%2C%20Glencoe%2C%20AL%2035905%2C%20United%20States&key=AIzaSyA_4Am7ZMP5bUtTjXchFxa8qLvG3KmAPlc"></iframe>
  </div>
  <div class="col-md-4">
    <p>Address:
        <br><strong>101 Hollingsworth Drive
        <br>Glencoe, AL 35905</strong>
    </p>
    <p>
      Conveniently located on the corner of US-431 and Hollingsworth Drive, between US-431 mile markers 249 and 250.
    </p>
    </div>
    <div class="clearfix"></div>
  </div>